def parts(x):
    if x == 0:
        print("---------------------|")
        print("|")
        print("|")
        print("|")
        print("|")
        print("|")
        print("------------")
    elif x ==1:
        print("----------------------|")
        print("|                     o")
        print("|")
        print("|")
        print("|")
        print("|")
        print("------------")
    elif x ==2:
        print("----------------------|")
        print("|                     o")
        print("|                     |")
        print("|")
        print("|")
        print("|")
        print("------------")
    elif x ==3:
        print("----------------------|")
        print("|                     o")
        print("|                     |")
        print("|                    /")
        print("|")
        print("|")
        print("------------")
    elif x ==4:
        print("----------------------|")
        print("|                     o")
        print("|                    /|")
        print("|")
        print("|")
        print("|")
        print("------------")
    elif x ==5:
        print("----------------------|")
        print("|                     o")
        print("|                    /|\ ")
        print("|")
        print("|")
        print("|")
        print("------------")
    elif x == 6:
        print("----------------------|")
        print("|                     o")
        print("|                    /|\ ")
        print("|                     |")
        print("|                     |")
        print("|")
        print("------------")
    elif x ==7:
        print("----------------------|")
        print("|                     o")
        print("|                    /|\ ")
        print("|                     |")
        print("|                    /|\ ")
        print("------------")